# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7f1428ff0c344039789a9d6318d5eff0e007e0732e5f7eb4172f0f07cb670bd9d13818f81574c7bd037e867d025f25598f2261f98b29fa8a820f510f33975eb

test:
  secret_key_base: a67764e7e390b9eac6ab38fb4a0cc12e6be6995d208aaebdd8877ade521f59795e23ca96396e80d1c6e97bfa8b20e49796180842bb41c90bb0ebda8f4cd7bc15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
